### ISSUE TITLE
TypeError [Error]: Cannot read properties of undefined (reading 'replace')

### ISSUE THREAD

**Issue by liujianying** [NXY666/Jsjiemi#101]
### 操作系统

MacOS

### Node.js 版本号

v16.20.2

### 问题详情

/Users/ljy/autjs/Jsjiemi-master/node_modules/vm2/lib/vm.js:290
                                throw bridge.from(e);
                                ^
Waiting for the debugger to disconnect...
TypeError [Error]: Cannot read properties of undefined (reading 'replace')
    at _0x902642 (vm.js:1:447)
    at vm.js:1:602
    at vm.js:1:657
    at Script.runInContext (node:vm:141:12)
    at VM.runScript (/Users/ljy/autjs/Jsjiemi-master/node_modules/vm2/lib/vm.js:288:18)
    at VM.run (/Users/ljy/autjs/Jsjiemi-master/node_modules/vm2/lib/vm.js:508:16)
    at virtualGlobalEval (/Users/ljy/autjs/Jsjiemi-master/Jsjiemi.js:863:19)
    at decryptGlobalJs (/Users/ljy/autjs/Jsjiemi-master/Jsjiemi.js:1305:3)
    at Object.<anonymous> (/Users/ljy/autjs/Jsjiemi-master/Jsjiemi.js:1325:19)
    at Module._compile (node:internal/modules/cjs/loader:1198:14)

### 目标代码

```JavaScript
curl 'https://bzjl.gitee.io/auto_hamibot_res/config/config_hamibot_bd_js_middle.js'
```

**Comment by NXY666** [comment]
我这里运行是正常的，我尝试了node16和node20都不会报错，不知道是不是系统的关系。
你试试把依赖删掉，不npm install直接运行？
